# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /posts/:title
paginate: 10 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Ameya Thakur
baseurl:   # Leave this blank unless you are using a directory other than the root directory (Do not use a trailing slash '/')
description: 'the blog of <span class="icon-arrow-big'></span>'
email: redsupercar@gmail.com
twitter: ameyathakur
icon_url: http://indiandennis.github.io/images/logo.jpg
disqus_shortname: 

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: 'url(http://indiandennis.github.io/images/banner.jpg)'
header_size: 'cover'
footer_background: 'url(http://indiandennis.github.io/images/footer.png)'
footer_size: 'cover'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title: 
footer_description: 
social_links_title: My Stuff
github_url: https://github.com/indiandennis
flickr_url: https://www.flickr.com/photos/ameyat
instagram_url: 
vimeo_url: 
facebook_url: 
google_plus_url: https://plus.google.com/+AmeyaThakurAT
pinterest_url: 
tumblr_url: 
linkedin_url: http://www.linkedin.com/in/indiandennis
dribbble_url: 
lastfm_url: http://www.last.fm/user/indiandennis
rdio_url: 
spotify_url: http://open.spotify.com/user/indiandennis
skype_url: 
soundcloud_url: http://www.soundcloud.com/indiandennis
behance_url: https://www.behance.net/ameyathakur
